### ISSUE TITLE
How to launch the first-ever-touchbar killer-app of yours ?

### ISSUE THREAD

**Issue by thabach** [erikolsson/Touch-Bar-Lemmings#1]
Hey Erik, how to launch the Lemmings for real 😳? 

Just forked your codebase, successfully built it in Xcode, ran a Product->Run and got the empty TouchLemmings window. Even in focus the first-ever-touchbar killer-app of yours doesn't make the Lemmings roam on my Touchbar - just yet. How to bring em on ? Please advise... 

Cheers, Christian.

**Comment by erikolsson** [comment]
he he honestly i only spent a few hours on this so I'm surprised that it built correctly :) did you try tapping the touch bar?

**Comment by thabach** [comment]
It all works ! so cool - found the reason for learning Swift now - thank you ! 🤓
