### ISSUE TITLE
'location(in:)' is only available on OS X 10.12.2 or newer' in file

### ISSUE THREAD

**Issue by linjaaho** [erikolsson/Touch-Bar-Lemmings#5]
I compiled and ran this and build failed with error message:

> 'location(in:)' is only available on OS X 10.12.2 or newer' in file 

on line 44 in file LemmingsScene.swift.

Fixed by changing line
`if #available(OSX 10.12.1, *)` to `if #available(OSX 10.12.2, *)`

(I think this is obvious for anyone familiar with Xcode and/or programming in general but just saying for people with no programming experience. I had to scratch my head couple of minutes, I have been using Xcode last time on year 2009.)

**Comment by linjaaho** [comment]
Wow, now Xcode even suggests the fix and does it for you if you click the red ball next to the error message. Much has happened in 7 years...

**Comment by 0xCardiE** [comment]
I had the same message, I fixed it to 12.2 but I just can't make this to work.
